"use client";
import { useState, useEffect } from "react";
import { supabase } from "../../../supabase";

export default function MyTeamTab() {
  const [user, setUser] = useState<any>(null);
  const [teamCode, setTeamCode] = useState("");
  const [myTeams, setMyTeams] = useState<{ id: number; name: string }[]>([]);
  const [loading, setLoading] = useState(false);
  const [message, setMessage] = useState({ type: "", text: "" });

  // 1. Get current logged-in user and fetch their teams on mount
  useEffect(() => {
    const getSessionAndTeams = async () => {
      const { data: { session } } = await supabase.auth.getSession();
      if (session?.user) {
        setUser(session.user);
        fetchMyTeams(session.user.id);
      }
    };
    getSessionAndTeams();
  }, []);

  // 2. Fetch all teams belonging to this user
  const fetchMyTeams = async (userId: string) => {
    const { data, error } = await supabase
      .from("teams")
      .select("id, name")
      .eq("profile_id", userId);

    if (!error && data) {
      setMyTeams(data);
    }
  };

  // 3. Handle claiming a team via code
  const handleClaimTeam = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!user) {
      setMessage({ type: "danger", text: "You must be logged in to claim a team." });
      return;
    }
    if (!teamCode.trim()) return;

    setLoading(true);
    setMessage({ type: "", text: "" });

    try {
      // Step A: Find the team with this code that hasn't been claimed yet
      const { data: team, error: fetchError } = await supabase
        .from("teams")
        .select("id, profile_id")
        .eq("team_code", teamCode.trim())
        .single();

      if (fetchError || !team) {
        setMessage({ type: "danger", text: "Invalid team code." });
        setLoading(false);
        return;
      }

      if (team.profile_id) {
        setMessage({ type: "danger", text: "This team has already been claimed." });
        setLoading(false);
        return;
      }

      // Step B: Update the row to populate profile_id
      const { error: updateError } = await supabase
        .from("teams")
        .update({ profile_id: user.id })
        .eq("id", team.id);

      if (updateError) throw updateError;

      // Step C: Success! Clear input, notify user, and refresh cards
      setMessage({ type: "success", text: "Team successfully claimed!" });
      setTeamCode("");
      fetchMyTeams(user.id);

    } catch (err: any) {
      setMessage({ type: "danger", text: "An error occurred while claiming the team." });
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="fade-in">
      {/* Title Header */}
      <div className="d-flex align-items-center gap-2 mb-4 text-primary">
        <i className="bi bi-people-fill fs-3"></i>
        <h4 className="fw-bold m-0 uppercase tracking-wide">My Teams</h4>
      </div>

      {/* Code Input Claim Box */}
      <div className="card p-4 border-0 bg-light mb-4 shadow-sm" style={{ borderRadius: "15px" }}>
        <div className="d-flex align-items-center gap-2 mb-2 text-dark">
          <i className="bi bi-shield-plus fs-5"></i>
          <h6 className="fw-bold m-0">Claim a New Team</h6>
        </div>
        <p className="text-muted small mb-3">
          Enter the unique access code generated by your tournament admin to add to your Leaderboard Statistics.
        </p>

        <form onSubmit={handleClaimTeam} className="row g-2">
          <div className="col flex-grow-1">
            <div className="input-group">
              <span className="input-group-text bg-white border-end-0 text-muted">
                <i className="bi bi-key-fill"></i>
              </span>
              <input
                type="text"
                placeholder="ENTER TEAM CODE"
                value={teamCode}
                onChange={(e) => setTeamCode(e.target.value)}
                disabled={loading}
                className="form-control border-start-0 text-uppercase font-monospace tracking-wider"
                style={{ outline: "none", boxShadow: "none" }}
              />
            </div>
          </div>
          <div className="col-auto">
            <button
              type="submit"
              disabled={loading}
              className="btn btn-primary px-4 fw-bold"
            >
              {loading ? (
                <>
                  <span className="spinner-border spinner-border-sm me-2" role="status" aria-hidden="true"></span>
                  Claiming...
                </>
              ) : (
                <>
                  <i className="bi bi-check-circle-fill me-2"></i>
                  Claim
                </>
              )}
            </button>
          </div>
        </form>

        {message.text && (
          <div className={`alert alert-${message.type} mt-3 mb-0 d-flex align-items-center gap-2 py-2 px-3`} style={{ borderRadius: "8px", fontSize: "0.85rem" }}>
            <i className={`bi ${message.type === "success" ? "bi-patch-check-fill" : "bi-exclamation-triangle-fill"}`}></i>
            <div>{message.text}</div>
          </div>
        )}
      </div>

      {/* Teams Grid Cards */}
      <div className="mt-4">
        {myTeams.length === 0 ? (
          <div className="text-center py-5 border rounded-3 bg-white" style={{ borderRadius: "15px", borderStyle: "dashed" }}>
            <i className="bi bi-person-x text-muted mb-2 block" style={{ fontSize: "2.5rem" }}></i>
            <h6 className="fw-bold text-dark mb-1">No teams linked yet</h6>
            <p className="text-muted small m-0">Get your team code from your admin</p>
          </div>
        ) : (
          <div className="row g-3">
            {myTeams.map((team) => (
              <div key={team.id} className="col-12 col-md-6">
                <div 
                  className="card border-0 shadow-sm p-3 h-100 bg-white team-card" 
                  style={{ borderRadius: "15px", transition: "all 0.2s ease-in-out", cursor: "pointer" }}
                >
                  <div className="d-flex align-items-center gap-3">
                    <div 
                      className="rounded-3 d-flex align-items-center justify-content-center text-primary bg-light" 
                      style={{ width: "48px", height: "48px", borderRadius: "12px" }}
                    >
                      <i className="bi bi-controller fs-4"></i>
                    </div>
                    <div className="flex-grow-1 overflow-hidden">
                      <h6 className="fw-bold text-dark m-0 text-truncate">{team.name}</h6>
                      <span className="badge bg-primary text-white mt-1" style={{ fontSize: "0.65rem", padding: "3px 8px" }}>
                        Team
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}