"use client";
import { useState, useEffect } from "react";
import { supabase } from "../../../supabase";

export default function MyTeamTab() {
  const [user, setUser] = useState<any>(null);
  const [teamCode, setTeamCode] = useState("");
  const [myTeams, setMyTeams] = useState<{ id: number; name: string }[]>([]);
  const [loading, setLoading] = useState(false);
  const [message, setMessage] = useState({ type: "", text: "" });

  // Claim confirmation state
  const [pendingTeam, setPendingTeam] = useState<{ id: number; name: string } | null>(null);

  // Remove/Unlink team state
  const [selectedTeamToRemove, setSelectedTeamToRemove] = useState<{ id: number; name: string } | null>(null);

  // 1. Get current logged-in user and fetch their teams on mount
  useEffect(() => {
    const getSessionAndTeams = async () => {
      const { data: { session } } = await supabase.auth.getSession();
      if (session?.user) {
        setUser(session.user);
        fetchMyTeams(session.user.id);
      }
    };
    getSessionAndTeams();
  }, []);

  // 2. Fetch all teams belonging to this user
  const fetchMyTeams = async (userId: string) => {
    const { data, error } = await supabase
      .from("teams")
      .select("id, name")
      .eq("profile_id", userId);

    if (!error && data) {
      setMyTeams(data);
    }
  };

  // 3. Step 1: Lookup team by code to confirm details before claiming
  const handleVerifyCode = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!user) {
      setMessage({ type: "danger", text: "You must be logged in to claim a team." });
      return;
    }
    if (!teamCode.trim()) return;

    setLoading(true);
    setMessage({ type: "", text: "" });

    try {
      const { data: team, error: fetchError } = await supabase
        .from("teams")
        .select("id, name, profile_id")
        .eq("team_code", teamCode.trim().toUpperCase())
        .single();

      if (fetchError || !team) {
        setMessage({ type: "danger", text: "Invalid team code." });
        return;
      }

      if (team.profile_id) {
        setMessage({ type: "danger", text: "This team has already been claimed." });
        return;
      }

      // Open confirmation prompt with found team
      setPendingTeam({ id: team.id, name: team.name });
    } catch (err: any) {
      setMessage({ type: "danger", text: "An error occurred while verifying the code." });
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  // 4. Step 2: Confirm and finalize claiming ownership
  const handleConfirmClaim = async () => {
    if (!pendingTeam || !user) return;
    setLoading(true);

    try {
      const { error: updateError } = await supabase
        .from("teams")
        .update({ profile_id: user.id })
        .eq("id", pendingTeam.id);

      if (updateError) throw updateError;

      setMessage({ type: "success", text: `Successfully claimed ${pendingTeam.name}!` });
      setTeamCode("");
      setPendingTeam(null);
      fetchMyTeams(user.id);
    } catch (err: any) {
      setMessage({ type: "danger", text: "Failed to claim team. Please try again." });
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  // 5. Remove team ownership (sets profile_id back to null)
  const handleRemoveTeam = async () => {
    if (!selectedTeamToRemove || !user) return;
    setLoading(true);

    try {
      const { error } = await supabase
        .from("teams")
        .update({ profile_id: null })
        .eq("id", selectedTeamToRemove.id);

      if (error) throw error;

      setMessage({ type: "success", text: `Removed ${selectedTeamToRemove.name} from your profile.` });
      setSelectedTeamToRemove(null);
      fetchMyTeams(user.id);
    } catch (err: any) {
      setMessage({ type: "danger", text: "Failed to remove team." });
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="fade-in">
      {/* Title Header */}
      <div className="d-flex align-items-center gap-2 mb-4 text-primary">
        <i className="bi bi-people-fill fs-3"></i>
        <h4 className="fw-bold m-0 uppercase tracking-wide">My Teams</h4>
      </div>

      {/* Code Input Claim Box */}
      <div className="card p-4 border-0 bg-light mb-4 shadow-sm" style={{ borderRadius: "15px" }}>
        <div className="d-flex align-items-center gap-2 mb-2 text-dark">
          <i className="bi bi-shield-plus fs-5"></i>
          <h6 className="fw-bold m-0">Claim a New Team</h6>
        </div>
        <p className="text-muted small mb-3">
          Enter the unique access code generated by your tournament admin to add to your Leaderboard Statistics.
        </p>

        <form onSubmit={handleVerifyCode} className="row g-2">
          <div className="col flex-grow-1">
            <div className="input-group">
              <span className="input-group-text bg-white border-end-0 text-muted">
                <i className="bi bi-key-fill"></i>
              </span>
              <input
                type="text"
                placeholder="ENTER TEAM CODE"
                value={teamCode}
                onChange={(e) => setTeamCode(e.target.value)}
                disabled={loading}
                className="form-control border-start-0 text-uppercase font-monospace tracking-wider"
                style={{ outline: "none", boxShadow: "none" }}
              />
            </div>
          </div>
          <div className="col-auto">
            <button
              type="submit"
              disabled={loading || !teamCode.trim()}
              className="btn btn-primary px-4 fw-bold"
            >
              {loading ? (
                <>
                  <span className="spinner-border spinner-border-sm me-2" role="status" aria-hidden="true"></span>
                  Checking...
                </>
              ) : (
                <>
                  <i className="bi bi-search me-2"></i>
                  Find Team
                </>
              )}
            </button>
          </div>
        </form>

        {message.text && (
          <div className={`alert alert-${message.type} mt-3 mb-0 d-flex align-items-center gap-2 py-2 px-3`} style={{ borderRadius: "8px", fontSize: "0.85rem" }}>
            <i className={`bi ${message.type === "success" ? "bi-patch-check-fill" : "bi-exclamation-triangle-fill"}`}></i>
            <div>{message.text}</div>
          </div>
        )}
      </div>

      {/* Teams Grid Cards */}
      <div className="mt-4">
        {myTeams.length === 0 ? (
          <div className="text-center py-5 border rounded-3 bg-white" style={{ borderRadius: "15px", borderStyle: "dashed" }}>
            <i className="bi bi-person-x text-muted mb-2 block" style={{ fontSize: "2.5rem" }}></i>
            <h6 className="fw-bold text-dark mb-1">No teams linked yet</h6>
            <p className="text-muted small m-0">Get your team code from your admin</p>
          </div>
        ) : (
          <div className="row g-3">
            {myTeams.map((team) => (
              <div key={team.id} className="col-12 col-md-6">
                <div 
                  onClick={() => setSelectedTeamToRemove(team)}
                  className="card border-0 shadow-sm p-3 h-100 bg-white team-card" 
                  style={{ borderRadius: "15px", transition: "all 0.2s ease-in-out", cursor: "pointer" }}
                >
                  <div className="d-flex align-items-center gap-3">
                    <div 
                      className="rounded-3 d-flex align-items-center justify-content-center text-primary bg-light" 
                      style={{ width: "48px", height: "48px", borderRadius: "12px" }}
                    >
                      <i className="bi bi-controller fs-4"></i>
                    </div>
                    <div className="flex-grow-1 overflow-hidden">
                      <h6 className="fw-bold text-dark m-0 text-truncate">{team.name}</h6>
                      <span className="badge bg-primary text-white mt-1" style={{ fontSize: "0.65rem", padding: "3px 8px" }}>
                        Team
                      </span>
                    </div>
                    <i className="bi bi-trash text-danger opacity-50 fs-5 hover-opacity-100 ms-auto"></i>
                  </div>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>

      {/* MODAL 1: Confirm Claiming Team */}
      {pendingTeam && (
        <div className="modal show d-block tab-modal-backdrop" tabIndex={-1} style={{ backgroundColor: "rgba(0,0,0,0.5)" }}>
          <div className="modal-dialog modal-dialog-centered">
            <div className="modal-content border-0 shadow" style={{ borderRadius: "16px" }}>
              <div className="modal-header border-0 pb-0">
                <h5 className="modal-title fw-bold">Confirm Team Claim</h5>
                <button type="button" className="btn-close" onClick={() => setPendingTeam(null)}></button>
              </div>
              <div className="modal-body py-4 text-center">
                <i className="bi bi-shield-check text-primary mb-2" style={{ fontSize: "3rem" }}></i>
                <p className="mb-1 text-muted">Are you sure you want to link to:</p>
                <h4 className="fw-bold text-dark">{pendingTeam.name}</h4>
                <p className="small text-muted mt-2">
                  Once linked, this team's statistics will be associated with your account profile.
                </p>
              </div>
              <div className="modal-footer border-0 pt-0 d-flex gap-2">
                <button 
                  type="button" 
                  className="btn btn-light flex-grow-1 fw-bold" 
                  onClick={() => setPendingTeam(null)}
                  disabled={loading}
                >
                  Cancel
                </button>
                <button 
                  type="button" 
                  className="btn btn-primary flex-grow-1 fw-bold" 
                  onClick={handleConfirmClaim}
                  disabled={loading}
                >
                  {loading ? "Claiming..." : "Yes, Claim Team"}
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* MODAL 2: Remove / Unlink Team Confirmation */}
      {selectedTeamToRemove && (
        <div className="modal show d-block tab-modal-backdrop" tabIndex={-1} style={{ backgroundColor: "rgba(0,0,0,0.5)" }}>
          <div className="modal-dialog modal-dialog-centered">
            <div className="modal-content border-0 shadow" style={{ borderRadius: "16px" }}>
              <div className="modal-header border-0 pb-0">
                <h5 className="modal-title fw-bold text-danger">Remove Team</h5>
                <button type="button" className="btn-close" onClick={() => setSelectedTeamToRemove(null)}></button>
              </div>
              <div className="modal-body py-4 text-center">
                <i className="bi bi-exclamation-octagon text-danger mb-2" style={{ fontSize: "3rem" }}></i>
                <p className="mb-1 text-muted">Remove team ownership for:</p>
                <h4 className="fw-bold text-dark">{selectedTeamToRemove.name}</h4>
                <p className="small text-muted mt-2">
                  This will unbind the team from your profile so someone else can claim it or you can re-claim it later with the code.
                </p>
              </div>
              <div className="modal-footer border-0 pt-0 d-flex gap-2">
                <button 
                  type="button" 
                  className="btn btn-light flex-grow-1 fw-bold" 
                  onClick={() => setSelectedTeamToRemove(null)}
                  disabled={loading}
                >
                  Cancel
                </button>
                <button 
                  type="button" 
                  className="btn btn-danger flex-grow-1 fw-bold" 
                  onClick={handleRemoveTeam}
                  disabled={loading}
                >
                  {loading ? "Removing..." : "Remove Team"}
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
